version: '3'

networks:
    nginx-php74-mysql8-node:

services:

    # nginx
    nginx-service:
        image: nginx:stable-alpine
        container_name: nginx
        ports:
            - "8000:80"
        volumes:
            - ../project_api_symfony:/var/www/project_api_symfony
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php74-service
            - mysql8-service
        networks:
            - nginx-php74-mysql8-node

    # php
    php74-service:
        build:
            context: .
            dockerfile: ./php/Dockerfile
        container_name: php74
        ports:
            - "9000:9000"
        extra_hosts:
            - "host.docker.internal:host-gateway"
        volumes:
            - ../project_api_symfony:/var/www/project_api_symfony
            - ./php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
        networks:
            - nginx-php74-mysql8-node

    # mysql
    mysql8-service:
        image: mysql:8
        container_name: mysql
        tty: true
        ports:
            - '3306:3306'
        volumes:
            - './ead_mysql:/var/lib/mysql'
            - './mysql:/docker-entrypoint-initdb.d'
        command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        restart: always # always restart unless stopped manually
        environment:
            MYSQL_ROOT_PASSWORD: 'secret'
            MYSQL_PASSWORD: 'secret'
        networks:
            - nginx-php74-mysql8-node

    # node
    node-service:
        image: node:latest
        container_name: node
        volumes:
            - ../project_api_symfony:/var/www/project_api_symfony
        working_dir: /var/www/project
        networks:
            - nginx-php74-mysql8-node
    
volumes:
    ead_mysql:
        driver: local